services:
  - type: web
    name: vartalaap-banking-blue
    env: docker
    region: singapore
    plan: free
    envVars:
      - key: DB_HOST
        fromDatabase:
          name: vartalaap-db-blue
          property: host
      - key: DB_PORT
        fromDatabase:
          name: vartalaap-db-blue
          property: port
      - key: DB_NAME
        fromDatabase:
          name: vartalaap-db-blue
          property: database
      - key: DB_USERNAME
        fromDatabase:
          name: vartalaap-db-blue
          property: user
      - key: DB_PASSWORD
        fromDatabase:
          name: vartalaap-db-blue
          property: password
      - key: DB_DRIVER
        value: org.postgresql.Driver
      - key: DB_DIALECT
        value: org.hibernate.dialect.PostgreSQLDialect

databases:
  - name: vartalaap-db-blue
    region: singapore
    plan: free
